### PR TITLE
Use as_deref instead of `as_ref.map`

### PR DESCRIPTION
**Pull request by lzutao**

### CODE REVIEW

**Comment by kennytm** [comment]
Why do you want to use a custom format?

**Comment by lzutao** [comment]
The default 80 width is  rather short in my opinion. I prefer longer one, which is 120.
Also the derive merging feature is not really nice as it leads to large
and multiline derive attribute.

**Comment by kennytm** [comment]
The default max width is 100 though. And the longest derive line in this package is `#[derive(StructOpt, Debug)]` so the `merge_derives = false` is useless.

If it's only about personal opinions I'd tend to close this PR.

**Comment by lzutao** [comment]
That's fair. I change it to deref change only.

**Pull request merged**
